#build stage
FROM node:22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_URL
ARG VITE_API_URL2
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_API_URL2=${VITE_API_URL2}
RUN npm run build

#copy static pages to nginx and serve them
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
