name: deploy_app
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          DFC_IAC_DEPLOY_KEY: ${{ secrets.DFC_IAC_DEPLOY_KEY }}
        run: |
              cd `mktemp -d` &&\
              echo "${DFC_IAC_DEPLOY_KEY}" > dfc_iac_deploy_key &&\
              chmod 400 dfc_iac_deploy_key &&\
              export GIT_SSH_COMMAND="ssh -i `pwd`/dfc_iac_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
              git clone git@github.com:data-for-change/dfc-iac.git &&\
              cd dfc-iac &&\
              git config --global user.name "Anyway CI" &&\
              git config --global user.email "anyway-ci@localhost" &&\
              git commit --allow-empty -m "automatic update of anyway (safety data)" &&\
              git push origin main
